version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: shin-kojirer-db
    environment:
      POSTGRES_DB: ordering_system
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U developer -d ordering_system"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: